version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/bec_lib"
    schedule:
      interval: "weekly"

  - package-ecosystem: "pip"
    directory: "/bec_server"
    schedule:
      interval: "weekly"

  - package-ecosystem: "pip"
    directory: "/bec_ipython_client"
    schedule:
      interval: "weekly"

  - package-ecosystem: "pip"
    directory: "/pytest_bec_e2e"
    schedule:
      interval: "weekly"
