version: 2
updates:
  - package-ecosystem: "pip"
    directories:
      - "/bec_lib"
      - "/bec_server"
      - "/bec_ipython_client"
      - "/pytest_bec_e2e"
    schedule:
      interval: "weekly"
    groups:
      shared-python-dependencies:
        patterns:
          - "*"
        group-by: "dependency-name"
