

include:
  - local: './ci/default-pipeline.yml'
    rules:
      - if: '$CI_PIPELINE_SOURCE == "schedule"'
      - if: '$CI_PIPELINE_SOURCE == "web"'
      - if: '$CI_PIPELINE_SOURCE == "pipeline"'
      - if: '$CI_PIPELINE_SOURCE == "parent_pipeline"'
      - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
      - if: $CI_COMMIT_BRANCH && $CI_OPEN_MERGE_REQUESTS
        when: never
      - if: $CI_COMMIT_BRANCH
      - if: '$CI_COMMIT_REF_NAME == "MR_DEV_BRANCH"'
        when: never
  - local: './ci/mr-dev-pages-pipeline.yml'
    rules:
      - if: '$CI_COMMIT_REF_NAME == "MR_DEV_BRANCH"'