redis:
  host: localhost
  port: 6379
file_writer:
  base_path: ./data
log_writer:
  base_path: ./logs
user_scripts:
  base_path: ./scripts
user_macros:
  base_path: ./macros
widgets_settings:
  base_path: ./widgets
scilog:
  env_file: ./
acl:
  acl_file: ./.bec_acl.env
