alignment: # AggregatedStateConfig -> can have different labels and for each label, different devices
  devices:
    samx:
      readback:
        value: 0
        abs_tol: 0.1
      velocity:
        value: 0
        abs_tol: 0.1
measurement:
  devices:
    samx:
      readback:
        value: 19
        abs_tol: 0.1
    samy:
      readback:
        value: 0
        abs_tol: 0.1
test:
  devices:
    samy:
      readback:
        value: 0
        abs_tol: 0.1