name: "BEC Install"
description: "Install BEC and related os dependencies"
inputs:
  BEC_CORE_BRANCH: # id of input
    required: false
    default: "main"
    description: "Branch of BEC Core to install"
  OPHYD_DEVICES_BRANCH: # id of input
    required: false
    default: "main"
    description: "Branch of Ophyd Devices to install"
  PYTHON_VERSION: # id of input
    required: false
    default: "3.11"
    description: "Python version to use"

runs:
  using: "composite"
  steps:
    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ inputs.PYTHON_VERSION }}

    - name: Checkout BEC Core
      uses: actions/checkout@v4
      with:
        repository: bec-project/bec
        ref: ${{ inputs.BEC_CORE_BRANCH }}
        path: ./bec

    - name: Checkout Ophyd Devices
      uses: actions/checkout@v4
      with:
        repository: bec-project/ophyd_devices
        ref: ${{ inputs.OPHYD_DEVICES_BRANCH }}
        path: ./ophyd_devices

    - name: Install Python dependencies
      shell: bash
      run: |
        pip install uv build

        # Build wheels for each package
        python -m build --wheel ./ophyd_devices
        python -m build --wheel ./bec/bec_lib
        python -m build --wheel ./bec/bec_ipython_client
        python -m build --wheel ./bec/bec_server

        # Install from wheels with dev dependencies
        uv pip install --system ./ophyd_devices[dev] ./ophyd_devices/dist/*.whl
        uv pip install --system ./bec/bec_lib[dev] ./bec/bec_lib/dist/*.whl
        uv pip install --system ./bec/bec_ipython_client[dev] ./bec/bec_ipython_client/dist/*.whl
        uv pip install --system ./bec/bec_server[dev] ./bec/bec_server/dist/*.whl
