name: Run Pytest with different Python versions
on: 
  workflow_call:
    inputs:
      pr_number:
        description: 'Pull request number'
        required: false
        type: number
      BEC_CORE_BRANCH:
        description: 'Branch of BEC Core to install'
        required: false
        default: 'main'
        type: string
      OPHYD_DEVICES_BRANCH:
        description: 'Branch of Ophyd Devices to install'
        required: false
        default: 'main'
        type: string
      BEC_WIDGETS_BRANCH:
        description: 'Branch of BEC Widgets to install'
        required: false
        default: 'main'
        type: string

jobs:
  pytest-matrix:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10", "3.11", "3.12"]

    steps:

      - name: Checkout BEC
        uses: actions/checkout@v4
        with:
          repository: bec-project/bec
          ref: ${{ inputs.BEC_CORE_BRANCH }}

      - name: Install BEC and dependencies
        uses: ./.github/actions/bec_install
        with:
          BEC_CORE_BRANCH: ${{ inputs.BEC_CORE_BRANCH }}
          OPHYD_DEVICES_BRANCH: ${{ inputs.OPHYD_DEVICES_BRANCH }}
          PYTHON_VERSION: ${{ matrix.python-version }}

      - name: Run Pytest
        run: |
          cd ./bec
          pytest -v --junitxml=report.xml --random-order ./bec_server/tests ./bec_lib/tests ./bec_ipython_client/tests/client_tests
